sipcapture/homer-app

public/app/widgets/protosearch-widget/widget/controllers/protosearch-widget.controller.js

This closes #6 
@lmangani @adubovikov please check if this fix solved the issue.

Clear protosearch widget form inputs when clear btn is pressed.

---

docker/Dockerfile

The size is still horrible but at least 314mb less horrible.
https://hub.docker.com/r/negbie/homer-app/tags -----------------> 176 MB
https://hub.docker.com/r/sipcapture/homer-app/tags ------------> 490 MB
Another thing I dislike:
added 1930 packages from 1430 contributors and audited 14164 packages in 46.894s
found 34 vulnerabilities (16 low, 14 moderate, 4 high)
run `npm audit fix` to fix them, or `npm audit` for details

Use node:8-alpine in Dockerfile

---

docker/docker-entrypoint.d/00-sed_files.sh

If the ports were changed via environment variables the generated configuration was invalid. The new port values were wrapped inside {} due to an incorrect variable expresssion.

Fix HTTP_PORT and HTTPS_PORT replacement

---

.gitignore
server/routes/export.js

This PR adds an API endpoint to export search results in the pcap format. We use this feature in Homer 5 and need this to be able to switch to Homer 7.
fixes #143

Export call data as pcap

---

server/routes/export.js

See https://github.com/sipcapture/homer/issues/335
The change is so radical that maybe I'm looking in the wrong place, but this works for me in a dev env with Homer 7.

Aims to fix issue 335

---

server/classes/searchdata.js

This PR Closes sipcapture/homer#378
It's related to sipcapture/homer#380 and sipcapture/homer#366
I noticed that when I looked up the calls manually, ordering by time in the database, the order was correct, narrowing it down to UI.
I tested it with some live data and flows and sorting by 'Date' work correctly.

removed postgres ROUND() function because it was

---

migrations/20191126194600_Datastructure.js

This PR 
- makes the knex migrations promised based
- throws errors if the migration cannot run  (for example ensuring that the error referenced [here](https://github.com/sipcapture/homer-app/issues/217#issuecomment-571767054) is thrown, not swallowed, by knex:migrate)
- and make sure knex:migrate doesn't die before tables are built
In the previous version of this migrate script, I noticed that if I put `console.log(exists)` right before the `if (!exists)` line, the value of `exists` wouldn't output to the terminal -- because the migration script didn't actually wait for the code inside of `hasTable` to run. This PR makes sure that the promises tied to both `hasTable` and `createTable` are returned. 
Additionally, when I ran the previous version of this migration script, my version of …

fix migration script

---

server/classes/ldap.js
server/config.js

**Background information**
We use Microsoft AD in our network to authenticate our users. While configuring LDAP authentication in Homer we ran into a limitation. In the current situation, it's only possible to bind to the AD using a distinguished name (DN). As far as I know, in Microsoft AD it's only possible to use the common name (CN) in the DN. In most cases, the CN is the full name of the user. Therefore, the full DN might look like `CN=John Doe,OU=Users,DC=contoso,DC=com`.
Instead of using the DN, we would like to use the user principal name (UPN) during authentication. In the current implementation, this is not possible since [this line](https://github.com/sipcapture/homer-app/blob/master/server/classes/ldap.js#L52) always appends the DN to the username. You can't leave the DN empty …

Add toggle to prevent appending the DN to the username

---

docker/docker-entrypoint.d/1
docker/webapp_config.json

Simply add
* "DB_KEEPALIVE=true"
to the homer-webapp section of docker-compose.yml to enable DB keepalive function
and e.g.
* "HOMER_LOGLEVEL=debug"
to the homer section docker-compose.yml to set specific logging level
Bash script portions and sed expressions tested.

Add logic to be able to supply DB_KEEPALIVE and HOMER_LOGLEVEL to Homer.

---

docker/webapp_config.json

Produces the rather confusing and counter-intuitive error message
No configuration file loaded:  While parsing config: invalid character '}' looking for beginning of object key string
panic: DB configuration file not found
etc

Fix trailing comma which prevents Homer from starting up.

---

docker/docker-entrypoint.d/1
docker/webapp_config.json

(i.e. whether a comma follows it or not)
Ensures that the keepalive boolean setting can appear on any row in the block (and optionally have a comma follow it) following later edits.

Simplify db keepalive startup setting

---

data/service/user.go
docker/webapp_config.json
etc/webapp_config.json
main.go
utils/ldap/ldap.go

These are all changes I needed to introduce in order to get Homer running with Microsoft AD on Windows. Plus, a few added niceties, like new debug logs, that helped me troubleshoot errors.
Main issue with existing approach is that it both relies on the LDAP user groups query returning **entries with `cn` attributes** and it **only** allows for the value of **`username` to be replaced in the filter template**. While simple to pull off on Open LDAP (i.e. Linux) by means of `memberUid`, default Active Directory installations typically store group memberships on a `member` attribute pointing to a list of fully qualified names, not usernames.
By introducing a new `"groupattribute"` setting, I was able to query groups following:
```json
"groupfilter": "(sAMAccountName=%s)",
"groupattribute": …
```

Allow pulling LDAP groups from any attribute

---

data/service/search.go

Добрый день !
Привык к алиасам в первых версиях семерки, а тут что-то поломались, этот патч фиксит, единственное,
надо добавить в "Fields Mapping":
{
"id": "aliasSrc",
"type": "string",
"index": "secondary",
"name": "aliasSrc",
"form_type": "input",
"hide": false
},
{
"id": "aliasDst",
"type": "string",
"index": "secondary",
"name": "aliasDst",
"form_type": "input",
"hide": false
}
По умолчанию, почему-то нет, после этого aliasSrc и aliasDst поля можно выбрать в "Column settings", соответственно
появятся и в табличке результатов поиска.

Fix in aliases

---

CONFIGURE.md
data/service/user.go
etc/webapp_config.json
main.go
utils/ldap/ldap.go

Added support for LDAP login as Admin and as User (issue https://github.com/sipcapture/homer-app/issues/328)
This requires changes to webapp conf file, with two new parameters that act similarly to their admin counterparts:
- usergroup
- usermode
Added support for recursive LDAP group search for Microsoft AD. This requred one optional parameter in config that is set by default to false. If set to true homer-app uses dn instead of username for resolving groups, as requred by 1.2.840.113556.1.4.1941 LDAP query.
- UseDNForGroupSearch

Kpribic ldap

---

data/service/search.go

We've been using homer and noted that when we have several network nodes reporting to a heplify-server cluster some dup packets are created with different Capture IDs. This code filters the dups only in the call flow. We've been using this for a while with no issues.

Filter dup packets in call flow

---

docker/docker-entrypoint.d/1
docker/webapp_config.json

Support for http_settings.path to be injected via HTTP_PATH environment variable. 
This will allow to serve the application in a relative path in the dockerized version of the application.

Support for http_settings.path to be injected via HTTP_PATH ENV

---

controller/v1/advanced.go
controller/v1/agentSub.go
controller/v1/authtoken.go
controller/v1/dashboard.go
controller/v1/hepsub.go
controller/v1/mapping.go

When `GetAgentsubByType()` is called from the API its parameters are currently being encoded on receipt - this seems incorrect.
Note that there are other methods in agentsSub.go which perform the same action so at this point I am flagging as draft as these may need patching too if agreed by the maintainers.

:bug: received parameters must be decoded, not encoded.

---

config/config.go
controller/v1/user.go
go.mod
main.go

In the oauth2 configuration, add a new config item `service_root` which will be used as the path for the 302 redirection to the application upon authentication by the service provider.
This value will default to `/`, so existing behavior will be unchanged.
This will allow for oauth to be used in installations where the application is not served directly from the root path
Also, `mod.go` was modified when building so I checked it in.  This does not affect my change so I can revert that if you'd like

add configurable service root to oauth config

---

etc/webapp_config.json
main.go

By default the echo server used in homer-app serves TLS 1.0.
Since both TLS 1.0 and TLS 1.1 are considered deprecated (see: https://datatracker.ietf.org/doc/rfc8996/) the minimum TLS version should therefore be configurable and set to TLS 1.2 as the default value.
Also support Mozilla profiles (restricts cipher suites based on TLS version)

Make TLS version configurable

---

go.mod
go.sum
migration/migration.go

Fixes #537 
Adds escaping for identifiers (table names, users, etc) using `pq.QuoteIdentifier`, and for literals using `pq.QuoteLiteral`. This allows usernames with characters like `-` and `@`, passwords with `'`, and resolves a SQL injection vulnerability.
Updates `github.com/lib/pq` to the latest version. It needed to be upgraded to at least [v1.2.0](https://github.com/lib/pq/releases/tag/v1.2.0), which added the `QuoteLiteral` function.
Verification done thus far:
- Ran homer image targeting a database with a regular username/password
- Ran homer targeting a GCP Cloud SQL database with IAM authentication (which has `-` and `@` in the username)
- Ran the initialization commands in the readme
- Loaded the image onto a dev environment with a real setup and poked around in it

Add Escaping for Identifiers and Literals in Migrations

---

utils/ldap/ldap.go

…pace-separated host strings
This update enhances the LDAP client by allowing it to connect to multiple LDAP servers. The 'Host' field now accepts a space-separated string of LDAP host addresses. The `Connect` method iterates over these hosts, attempting to establish a connection with each one until a successful connection is made.
Key changes:
- Split the 'Host' field into individual host addresses.
- Iterated over each host to attempt a connection.
- Implemented error handling to try the next host if a connection fails.
- Updated the connection logic to support both non-SSL and SSL connections, including handling TLS upgrades.
This change improves the robustness of the LDAP client by ensuring that the application can failover to another LDAP server if the primary server is unavailable.

Add support for connecting to multiple LDAP hosts

---

config/config.go
controller/v1/user.go
etc/webapp_config.json
main.go

Some OAuth provider do not have support for PKCE. This PR uses a feature flag to use/not use PKCE-specific fields during OAuth process.
Default is the current behaviour where PKCE is enabled

Enables optional handling of PKCE

---

docker/docker-entrypoint.d/1
docker/webapp_config.json

There are 2 issues where "homer_user" as a LDAP usergroup name clashes with db user in entrypoint.sh as mentioned here: [](https://github.com/sipcapture/homer/issues/592#issuecomment-2253164973)
https://github.com/sipcapture/homer7-docker/issues/145
https://github.com/sipcapture/homer/issues/592
This PR will fix the issue.

fix for using 'homer_user' as ldap groupname

---

controller/v1/user.go
data/service/user.go
model/user.go
swagger.json

Prevents login if user is not enabled
( I think this should be enough to add the properties to the DB and UI, and at its simplest, prevent login if the user is not enabled. Did I miss anything database-wise? )
Feedback welcome.

Add new user property: enabled

---

data/service/hepsub.go

Fixes [https://github.com/sipcapture/homer-app/security/code-scanning/14](https://github.com/sipcapture/homer-app/security/code-scanning/14)
To fix the problem, we need to ensure that the JSON string produced by `json.Marshal` is properly escaped before embedding it into another JSON string. The best way to fix this is to avoid manually constructing the JSON string and instead use a structured approach to build the JSON response.
We can use a map to construct the JSON response and then marshal the entire map to a JSON string. This approach ensures that all necessary escaping is handled by the `json.Marshal` function.

Fix code scanning alert no. 14: Potentially unsafe quoting

---

data/service/agentSub.go

Fixes [https://github.com/sipcapture/homer-app/security/code-scanning/1](https://github.com/sipcapture/homer-app/security/code-scanning/1)
To fix the problem, we need to use parameterized queries instead of string concatenation to construct the SQL query. This will ensure that user input is properly escaped and cannot be used to inject malicious SQL code.
- Replace the `fmt.Sprintf` function with a parameterized query using placeholders.
- Pass the `typeRequest` parameter as an argument to the `Where` method to safely embed it into the query.

Fix code scanning alert no. 1: Database query built from user-controlled sources

---

data/service/agentSub.go

Fixes [https://github.com/sipcapture/homer-app/security/code-scanning/2](https://github.com/sipcapture/homer-app/security/code-scanning/2)
To fix the problem, we should use parameterized queries instead of string concatenation to construct the SQL query. This approach ensures that user-provided values are properly escaped and cannot be used to inject malicious SQL code.
In the `GetAgentsubAgainstGUIDAndType` function, we will replace the `fmt.Sprintf` method with a parameterized query using placeholders (`?`) for the user-provided values (`guid` and `typeRequest`). We will then pass these values as arguments to the `Where` method.

Fix code scanning alert no. 2: Database query built from user-controlled sources

---

data/service/search.go

Fixes [https://github.com/sipcapture/homer-app/security/code-scanning/3](https://github.com/sipcapture/homer-app/security/code-scanning/3)
To fix the problem, we need to use parameterized queries instead of string concatenation to safely embed user input into the SQL query. This can be achieved by using the `gorm` library's query parameterization features.
- Replace the string concatenation in the `GetTransactionData` function with parameterized queries.
- Modify the `GetTransactionData` function to accept additional parameters for the `whitelist` values and use them in the query safely.

Fix code scanning alert no. 3: Database query built from user-controlled sources

---

data/service/userSettings.go

Fixes [https://github.com/sipcapture/homer-app/security/code-scanning/10](https://github.com/sipcapture/homer-app/security/code-scanning/10)
To fix the problem, we should ensure that user-provided data is safely embedded into the SQL query using parameterized queries or prepared statements. This can be achieved by modifying the `Where` clause to use placeholders and passing the user-provided values as parameters. This approach prevents SQL injection by ensuring that the user input is treated as data rather than executable code.

Fix code scanning alert no. 10: Database query built from user-controlled sources

---

data/service/userSettings.go

Reverts sipcapture/homer-app#587

Revert "Fix code scanning alert no. 10: Database query built from user-controlled sources"

---

data/service/userSettings.go

Fixes [https://github.com/sipcapture/homer-app/security/code-scanning/9](https://github.com/sipcapture/homer-app/security/code-scanning/9)
To fix the problem, we should ensure that user-provided values are safely embedded into the SQL query using parameterized queries. GORM already provides a way to safely handle user input by using maps in the `Where` method. However, we should explicitly use parameterized queries to ensure that the values are properly escaped.
We will modify the `Get`, `Delete`, and `Update` methods in the `UserSettingsService` to use parameterized queries with named placeholders. This will ensure that the user-provided values are safely embedded into the SQL query.

Fix code scanning alert no. 9: Database query built from user-controlled sources

---

main.go

if webapp is located behind the an ALB with specific route path - this URL doesn't work

fix path for swagger
