sipcapture/homer-app

public/app/filters/index.js, public/app/filters/message-search/index.js, public/app/filters/message-search/message-search.js
This closes #15 
@lmangani @adubovikov please check if this fix solved the issue.
=> Port messageSearch filter.

public/app/search/call-search/controllers/call-search.controller.js
This fixes #12 
@lmangani @adubovikov please check if this fix solved the issue.
=> Use sweetalert2 for the callSearch filter.

server/classes/searchdata.js
=> Handle cases when elems is one of the following: undefined, null or object

server/classes/searchdata.js
=> Use lodash methods to avoid bad implementation errors in searchdata class

public/css/new-design/style.css
=> scroll-grid height fixed

README.md, docs/dev/README.md, docs/dev/angularjs_widget_dev.md, docs/dev/react_widget_dev.md, docs/dev/troubleshooting.md
Create docs structure.
Add widget AngularJS dev documentation.
Update angularjs_widget_dev.md
=> Add widget AngularJS dev documentation.

public/app/directives/auto-fill-sync.js, public/app/directives/index.js, public/app/login/login-user/templates/login-user.template.html
This closes #55 
Tested on the following browsers: Chrome 70 and Firefox 58.
Result
=> Add autoFillSync directive to update ng-model in case of input auto-filling by a browser

server/routes/authentication.js, server/routes/users.js
This closes #58 
@lmangani please look at it and merge if it is ok.
=> Decrease required length for some string parameters for the routes.

package-lock.json, public/app/app.module.js, public/app/components/index.js, public/app/components/smart-table-with-dynamic-options/_smart-table-with-dynamic-options-edit.html, public/app/components/smart-table-with-dynamic-options/_smart-table-with-dynamic-options-edit.js, public/app/components/smart-table-with-dynamic-options/index.js, public/app/components/smart-table-with-dynamic-options/smart-table-with-dynamic-options.html, public/app/components/smart-table-with-dynamic-options/smart-table-with-dynamic-options.js, public/app/sections/header-navbar/app-preferences/components/app-preferences-users/controllers/app-preferences-users.controller.js, public/app/sections/header-navbar/app-preferences/components/app-preferences-users/templates/app-preferences-users.template.html
@lmangani @adubovikov 
Smart table with dynamic options.
Possible improvements:
1. Lifting the state. It is related to the whole app, not only this component
2. Row edit modal form. Add validation
3. Row edit modal form. Handle different type of values differently. For example, if a value of the boolean type - render a checkbox, if a number - render number input etc.
ATTENTION! The last commit is refactored settings users. It was done to demo the component. Probably the commit should be removed.
Screenshots:
Display table
Edit row
New row
Delete
=> Smart table with dynamic options

public/app/app.config.js, public/app/sections/header-navbar/app-preferences/index.js, public/app/sections/header-navbar/header-navbar/header-navbar.component.js
This closes #80
@lmangani @adubovikov The `globalsettings` resolved object is among the lifted objects. Now it is resolved as early as possible, in the root state. Check it and marge if ok.
=> Lifting state up by placing all header level resolved objects to the hepic root state.

public/app/login/login-user/controllers/login-user.controller.js, public/app/login/login-user/templates/login-user.template.html, public/app/login/services/authentication/authentication.service.js
=> Login page notifications fix

public/css/new-design/style.css
=> fix icons overflow

public/css/new-design/style.css
=> UIGrid dropdown menu fix

public/app/search/call-search/controllers/call-search.controller.js
Destroy timechange event listeners on call search component destroy
=> Fix CallSearch Event Listeners 

public/app/search/call-detail/call-detail/controllers/call-detail.controller.js
Handle empty data / request error and hide Flow or QoS tabs
=> Hide Flow and QoS tabs if data is unavailable

public/app/sections/header-navbar/app-preferences/controllers/app-preferences.controller.js, public/app/sections/header-navbar/header-navbar/controllers/header-navbar.controller.js, public/app/sections/header-navbar/header-navbar/templates/header-navbar.template.html
Fix Preference navbar link
Now you can use links for a tab.
For example: `http://localhost/#!/preferences/mapping/protocol`
=> Preferences link fix

public/app/search/call-search/controllers/call-search.controller.js, public/app/search/remote-search/controllers/remote-search.controller.js, public/css/new-design/style.css
Reverts sipcapture/homer-app#166
=> Revert "Issue 146"

public/css/new-design/style.css
Updated table styles to fit user screen
=> #169 - UI grid takes window fullsize

server/routes/alias.js
https://github.com/sipcapture/homer-app/issues/171
=> fix: In alias tab cannot save unless you mark status true

docker/docker-entrypoint.d/9
I believe these are typos in the Docker db provisioning script
=> docker db provisioning fixes

homer-app.yaml
/lib/systemd/system/: units provided by installed packages
/etc/systemd/system/: units installed by the system administrator
=> move service file to systemd stock directory

data/service/search.go
The whole query building needs still a lot of love and should be moved out into a seperate function but for my tests this was the only thing I needed right now.
=> Allow multiple values with wildcards

main.go
Hey, I wanted to test the non docker version and got immediately bored by the Readme instructions. The only thing I want is to see at the top of the Readme is some lines of text and in the best case lot's of cat pics but not Create User, Create Role, Create DB, bake a cake, visit your grandma and so on. Just give the user a init func for the first time ;) Like
./homer-app -initialize_db -database-host=localhost -database-root-user=postgres -database-root-password=root
=> Add initDB func

data/service/search.go
Logical or can be activated per field by the prefixing ||
It won't be applied for the first field because this would bypass the time criteria.
For example
Method: ||PRACK;INVITE%
Dst Port: ||5060
Will be this Query:
{"level":"info","module":"gorm","msg":"SELECT * FROM \"hep_proto_1_call\"  WHERE (create_date between $1 AND $2 AND data_header-\u003e\u003e'method' LIKE ANY ('{PRACK,INVITE%}') OR protocol_header-\u003e\u003e'dstPort' \u003c\u003e '5060') LIMIT 200","time":"2020-02-16T15:35:26+01:00","type":"sql"}
=> Seperate buildQuery and logical or

controller/v1/search.go, model/search.go
contains no actual code change but only swagger annotations so can be safely merged.
=> added swagger docs for search apis

docker/docker-entrypoint.d/9
FIx for https://github.com/sipcapture/homer-app/issues/311
=> correction for param -database-root-user

controller/v1/advanced.go, controller/v1/agentSub.go, controller/v1/alias.go, controller/v1/authtoken.go, controller/v1/dashboard.go, controller/v1/grafana.go, controller/v1/hepsub.go, controller/v1/hepsubsearch.go, controller/v1/mapping.go, controller/v1/profile.go, controller/v1/prometheus.go, controller/v1/remote.go, controller/v1/search.go, controller/v1/statistic.go, controller/v1/user.go, controller/v1/userSettings.go, main.go, model/authToken.go, model/hepsub.go, router/v1/agentsSub.go, swagger.json
I tried to do what I could with updating swagger to the correct URIs and HTTP methods.  I was not able to test all of the calls via swagger.  I think the swagger stuff needs significant review beyond this PR.  
Some of the swagger models that reference certain structs are very confusing, also the responses in the swagger definition.  Those are very confusing or lacking.  I attempted to look at schema definitions and add or update where I could but those were confusing as well.
It would definitely be helpful to add additional models or parameters so users like myself know what data to pass.  Same goes for the responses.
=> Fix swagger defs

docker/docker-entrypoint.d/1
(Homer can now start up with this change)
=> Fix trailing comma also in startup sed script for docker... *facepalm*

utils/ldap/ldap.go
I was trying to get Homer to work with LDAP authentication, but kept silently failing for me. I noticed there were barely any error or debug logs for most points of failure following the LDAP login flow - which leaves users pretty much in the dark when debugging these sort of issues. Adding a bunch of them help me troubleshoot a config error: had a minor typo in my `ldap_config.base` setting.
This may help others experiencing the same.
=> Add LDAP login error logs

data/service/dashboard.go
Noticed this in the postgresql logs.
=> Fix missing parenthesis

controller/v1/search.go
This PR makes it possible to use subnet masks when creating alias in homer.
I've only added them in SearchData and GetTransaction but it might make sense to add them to other places as well.
=> Allow usage of subnet masks for alias

docker/docker-entrypoint.d/1
Added homer docker LDAP variables override
=> Docker LDAP variables override

data/service/agentSub.go, model/search.go
This provides support for seeking and retrieving files from HEPSUB agents, including support for multiple agent subscriptions.
=> :sparkles: Allow file download from HEPSUB subscribers

config/config.go, controller/v1/grafana.go, data/service/grafana.go, etc/webapp_config.json, router/v1/grafana.go, version.go
Re: https://github.com/sipcapture/homer-ui/issues/593
=> Add grafana path

docker/docker-entrypoint.d/1, docker/webapp_config.json
=> :wrench: enable API key auth to be enabled via docker config

data/service/user.go
This PR validates an OAUTH user agains the DB to check if it has admin rights.
=> Oauth admin user

docker/docker-entrypoint.d/1, docker/docker-entrypoint.d/9, docker/webapp_config.json
Hello. It would be good to give possibility to override database port value in entrypoint script
=> Adding possibility to parametrize db port value

data/service/user.go
Fixes [https://github.com/sipcapture/homer-app/security/code-scanning/4](https://github.com/sipcapture/homer-app/security/code-scanning/4)
To fix the problem, we need to ensure that user-provided data is safely embedded into the database query. This can be achieved by using parameterized queries or prepared statements provided by the ORM. In this case, we will use the ORM's parameterization features to safely include the `GUID` and `UserName` values in the query.
1. Modify the `GetUserByUUID` method in `data/service/user.go` to use parameterized queries.
2. Ensure that the `sqlWhere` map is constructed in a way that the ORM can safely handle the parameters.
=> Fix code scanning alert no. 4: Database query built from user-controlled sources
